name: "django-practice"
owner: "nmatsui"
aws:
  region: "ap-northeast-1"
  rds:
    instancetype: "db.m1.small"
    storagesize: 5
    dbname: "djangodb"
    user:
      name: "djangopractice"
      password: ""
  elb:
    healthcheck: "HTTP:80/"
    instance:
      instancetype: "t2.micro"
      ami: "ami-a21529cc"
      keyname: ""
    autoscaling:
      max: 2
      min: 2
      desired: 2
