- hosts: all
  gather_facts: yes
  vars_files:
    - group_vars/packer_vars.yml
  roles:
    - role: setup_os
    - role: install_lib
    - role: install_python
    - role: setup_django_app
    - role: setup_gunicorn
    - role: setup_nginx
