- name: "copy & unarchive django app"
  unarchive: src={{ server.app_name }}.tar.gz dest={{ aliases.home }} creates={{ aliases.app_path }}
  register: set_app_sources

- name: "pip install -r requirements.txt"
  shell: |
    pip install -r requirements.txt
  args:
    chdir: "{{ aliases.app_path }}"
  environment:
    PATH: "{{ aliases.path }}"
  when: set_app_sources.changed

- name: "collect staticfile"
  shell: |
    python manage.py collectstatic --noinput
  args:
    chdir: "{{ aliases.app_path }}"
  environment:
    PATH: "{{ aliases.path }}"
  when: set_app_sources.changed
